services:
  # PostgreSQL Database
  database:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amigos
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - spring-postgres
    restart: unless-stopped

  # Spring Boot Application
  app:
    container_name: spring-boot-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/amigos
      - SPRING_DATASOURCE_USERNAME=amigoscode
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - database
    networks:
      - spring-postgres
    restart: unless-stopped

volumes:
  postgres:

networks:
  spring-postgres:
