services:
    image: postgres:latest
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
    volumes:
    ports:
      - "5332:5432"
    networks:
    restart: unless-stopped

    networks:

volumes: